Design docs
urbit/new-mars pull request #2
Opened 2022-03-29 22:14 UTC by eamsden

2022-03-30 13:57 UTC, joemfb requested changes
These look great! I found a couple things:

2022-03-30 13:57 UTC, joemfb commented on docs/heap.md
> +Allowing metadata to be attached to heap entries
This got cut off.

2022-03-30 13:57 UTC, joemfb commented on docs/llvm.md
> +| `ir[s 1 [12 b c]]       | `puh[1]; ir[1 1 b]; put[0]; ir[s 1 c]; cel[0]; spy; pop
Missing some closing `` ` ``s here.

2022-03-30 13:57 UTC, joemfb commented on docs/subject-knowledge.md
> +Otherwise the result is `[%dice ~]` whether or not the atom result of the subformula is known.
It can only be `%dice` if the subformula is known or dice, right?

2022-03-30 23:55 UTC, eamsden commented on docs/heap.md
> +Allowing metadata to be attached to heap entries
Thanks, fixed

2022-03-31 01:55 UTC, joemfb commented on docs/llvm.md
> +| `ir[s 1 [12 b c]]       | `puh[1]; ir[1 1 b]; put[0]; ir[s 1 c]; cel[0]; spy; pop`
One more backtick here.

2022-03-31 01:55 UTC, joemfb commented on docs/subject-knowledge.md
> +Otherwise the result is `[%dice ~]` whether or not the atom result of the subformula is known.
Thanks, this makes sense.

2022-03-31 13:40 UTC, merged