[ares] add basic ipc handler
urbit/new-mars pull request #21
Opened 2023-02-11 09:55 UTC by philipcmonk

This is a pretty minimal implementation of the newt protocol used by the king.  It works, in the sense that the vere king starts up with this serf process and tries to replay, then passes in events, which we can print out here.  Obviously, we don't actually run the events, we just report success.

2023-02-12 00:32 UTC, philipcmonk commented
Added another commit which expands the functionality to actually run events.  With the included "baby" pill (which is a degenerate "arvo" that requires no jets), I was able to boot and handle events with vere's king.

2023-02-13 14:20 UTC, eamsden requested changes

2023-02-13 14:20 UTC, eamsden commented on rust/ares/src/interpreter.rs
> +    newt: &mut Option<&mut Newt>,
It would be good to have a comment regarding the purpose of the `newt` argument and the expected behavior in the `Some` and `None` cases.

2023-02-13 14:20 UTC, eamsden commented on rust/ares/src/interpreter.rs
> +                    if let Ok(found) = match_pre_hint(stack, subject, hint_cell) {
Can we have a comment explaining the `pre_` vs `post_` distinction for hint matching? I figured it out but it took a bit. Even something like `hint matching, tree preorder` vs `hint matching, tree postorder`

2023-02-13 14:20 UTC, eamsden commented on rust/ares/src/newt.rs
> +                    indirect.data_pointer() as *const u8,
Does the data need to be copied out of the indirect atom to be written? Could we just write the size from the buffer and then the data directly from the indirect atom's data pointer?

2023-02-13 14:20 UTC, eamsden commented on rust/ares/src/newt.rs
> +        // when these are aligned to bytes
Have a look at what `jam()` does.

2023-02-13 18:14 UTC, merged